# Generated by Django 4.1.7 on 2023-05-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appModaDjango', '0002_lineascredito_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.RemoveField(
            model_name='lineascredito',
            name='id',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.TextField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lineascredito',
            name='codigo',
            field=models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='codigo'),
        ),
    ]
