# Generated by Django 4.1.7 on 2023-05-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appModaDjango', '0003_remove_cliente_id_remove_lineascredito_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credito',
        ),
    ]
