# Generated by Django 4.1.7 on 2023-05-16 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appModaDjango', '0004_delete_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveBigIntegerField(verbose_name='Total crédito')),
                ('plazo', models.PositiveSmallIntegerField(choices=[('m', 6), ('m', 12), ('m', 18), ('m', 24)], default=6, verbose_name='Plazo')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appModaDjango.lineascredito')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appModaDjango.cliente')),
            ],
        ),
    ]
