# Generated by Django 4.1.7 on 2023-05-16 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appModaDjango', '0005_credito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credito',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='credito',
            name='documento',
        ),
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.DeleteModel(
            name='credito',
        ),
        migrations.DeleteModel(
            name='lineasCredito',
        ),
    ]
