# Generated by Django 4.1.7 on 2023-05-16 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appModaDjango', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credito',
            name='plazo',
            field=models.PositiveSmallIntegerField(choices=[(6, 6), (12, 12), (18, 18), (24, 24)], default=6, verbose_name='Plazo'),
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.TextField(max_length=30)),
                ('clave', models.TextField(max_length=30)),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appModaDjango.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=30)),
                ('apellido', models.TextField(max_length=30)),
                ('celular', models.PositiveBigIntegerField(verbose_name='Teléfono celular')),
                ('documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appModaDjango.usuario')),
            ],
        ),
    ]
